= Face Toolbox Overview
:showtitle:
:revdate: 2025-01-03

== Overview
This toolbox contains a description of the process, tools, and materials needed to construct and use a selection of PAD-L1 face PAIs (see the Toolbox Overview for more information about PAD levels). As there is an almost unlimited number of possible PAIs that can be created at any PAD level, the set of PAIs here are considered a representative set of PAIs, not an exhaustive set.

There are two categories of face artefacts that can be used for presentation attacks. The first is two-dimensional (2D), such as a printed photo of a target user. The second is three-dimensional (3D), for example, a face mask that mimics the geometry of a user's face. This toolbox describes 2D face artefacts that the evaluator shall create for PAD testing.

There are also two types of face biometric verification methods, 2D or 3D image-based methods. The 2D image-based method captures a two-dimensional face image with a sensor using visible light to recognize a person. The 3D image-based method creates three-dimensional model of the human face using a 3D scanner such as a depth camera.

== Face Presentation Attacks
=== 2D Attacks
There are many research papers that study face presentation attacks. In these papers, researchers typically create 2D face artefacts through the following process.

. Capture face images of a target user using a camera.

. Print the captured image on paper or display the captured image on a screen. This is now referred to as a 2D face artefact.

. Present a 2D face artefact to the TOE.

Presentation attacks with 2D face artefacts can be categorized into the following three types based on the tools or materials used.

* printed photo attack
+
An attacker attempts to spoof the TOE using a captured face image printed on paper

* digital photo attack
+
An attacker attempts to spoof the TOE using a captured face image displayed on a screen

* replay video attack
+
An attacker attempts to spoof the TOE using a recorded face video replayed on a screen

=== 3D Attacks
In this toolbox, the specific 3D face artefacts are limited to those created from 2D output.

- Printed face mask
+
Printed photo is bent and worn as a face mask to create the illusion of a real 3D face.

== Face Presentation Attack Detection
=== 2D Detection
Images captured by the TOE from the 2D face artefacts may visually look very similar to images captured of a human, however, they are not exactly the same. For example, paper and screens containing the artefacts reflect light in different ways than humans do, because humans are complex non-rigid 3D objects and the artefacts are planar rigid objects. The surface properties of real faces and face artefacts (e.g., pigments) are also different. In addition, face artefacts may contain moiré patterns--an undesired aliasing of images produced during various image display and image acquisition processes. The TOE can detect such differences to detect and prevent presentation attacks.

=== 3D Detection
The printed face mask may contain quality defects that result in an appearance difference from a genuine human face. For example, the skin texture and detailed facial structures present in a printed face mask have perceivable differences compared to those in real faces. The printed face mask also may lack the facial motions, such as expression changes, eye blinks, and mouth movements, because it is made of rigid materials. Several PAD methods that utilize such cues have been studied and reported by researchers. Other PAD methods utilize liveness cues, such as thermal signatures, gaze information, and pulse or heartbeat signals, to detect a printed face mask. However, normally such design information of the PAD is not available to the evaluator and the TOE must be tested in black box manner.

== Common Test Protocol
Face PAD testing can be performed in a variety of ways. The evaluator can use different types of cameras under different illuminations to capture face images of test users to create face artefacts. The evaluator can also present these artefacts under different conditions. It's not possible to cover all such test scenarios. This toolbox defines a common test protocol to maintain consistency among different PAD testing environments. The evaluator shall follow the test protocols described below, in addition to guidance provided in Toolbox Overview, to conduct the PAD testing.

The tools and media for the creation of artefacts are defined for all tests in the link:Face_Toolbox_Inventory.adoc[Face Toolbox Inventory]. Each attack specifies which tools and media are to be used in the creation of artefacts for that test.

=== Initial Preparation - All Artefacts

. Enrolment
.. The evaluator shall enable face unlock and enrol the test users following instructions provided by the AGD guidance (i.e., test users should not wear glasses, hat, or heavy make-up during the enrolment if the guidance instructs not to do so).
.. The evaluator shall enrol test users' neutral (i.e., expressionless) frontal faces under the controlled environment where the background of the scene is uniform, the light in the room is switched on, and the window blinds are down (i.e., direct external lighting is blocked). 

. Face image capture
.. The evaluator shall capture face images immediately following the enrolment of test users under identical environmental conditions to reduce the possibility that the artefacts are rejected because differences in illumination, background scene, or expression.
.. The evaluator shall capture test users' face images with Type 1 (i.e., "normal" quality) and Type 2 (i.e., "high" quality) cameras for printed and digital photo attacks. The evaluator shall also record video of the user's face for ten seconds for reply video attacks. 

=== 2D Artefacts - Photos and Video
[start=3]
. Artefact creation
.. The evaluator shall print face images on paper for printed photo attacks, display face images on a screen for digital photo attacks, and replay face videos on a screen for replay video attacks. The size of face images on artefacts shall be same as the test user's face.

. Artefact presentation
.. The evaluator shall present artefacts to the TOE in the identical controlled environment used during enrolment.
.. The evaluator shall adjust the distance between artefacts and the TOE so that the TOE can't see the edge of artefacts and to minimize moiré patterns.
.. The evaluator shall present artefacts in a way that minimizes reflections from ambient lighting.
.. The evaluator shall present artefacts by hand for printed and digital photo attacks, introducing some noticeable motion, and by tripod for replay video attack.

=== 3D Artefacts - Worn Photo Face Mask
[start=3]
. Artefact creation
.. The evaluator shall print face images for printed photo attacks. The size of face images on artefacts shall be same as the test user's face.

. Artefact presentation
.. The evaluator shall bend and wear the printed face mask using tape or paste and present it to the TOE under the identical controlled environment used during enrolment.
.. The evaluator shall present printed face masks in a way that minimizes reflections from ambient lighting.

== Stored Artefact Usage
If stored artefacts will be used for testing, a number of fresh artefacts are still required to ensure that stored artefacts have not degraded in non-visible ways that would effect the testing. Stored artefacts also have maximum ages based on the date of initial creation (weeks are used for consistent time periods). Stored artefacts can only be used up to the maximum age based on the time difference between the creation date and the use date (use must be completed before the maximum age allowed).

The following table specifies the maximum amount of stored artefacts that can be used for each type and the maximum age allowed for the artefacts to be used.

[cols=".^3,.^2,.^2",options="header",]
|===

|Artefact type
|Max stored artefacts allowed
|Max age of stored artefacts

|2D Artefacts - Photos and Video
|None allowed
|Not applicable

|3D Artefacts - Worn Photo Face Mask
|None allowed
|Not applicable


|===

== Requirements for Tools
The evaluator needs to use several tools, such as cameras, screens, printers, and media, that meet the specifications listed below, since these specifications impact the clarity or sharpness of face artefacts. For example, the quality of digital photos depends on the screen resolution. If the screen is 4K (i.e., a horizontal screen resolution in the order of 4,000 pixels), and it can provide the finest clarity and detail of face images.

This toolbox defines two level of tools--Type 1 and Type 2--to cover variety of tools to conduct the PAD testing efficiently. Not all tools have both levels.

Type 1 tools are inexpensive and can be used by novices to capture and upload images to social media. An attacker may also create face artefacts with such uploaded images without difficulty. Detailed attack methods using uploaded images have been published on the Internet, so the evaluator shall try this type of artefact first. 

Type 2 tools have better performance (e.g., higher resolution) than Type 1 tools.  Such tools should be the latest available (for example, a device that has been recently released, or is considered an industry leading device of that type). Those tools may be expensive, but may be rented at an affordable cost. The reason why such tools should be used is that the PAD algorithm may show good rejection performance for artefacts used to train the algorithm, but reduced rejection performance for artefacts the algorithm has never seen before. Attackers may additionally create high-quality artifacts to maximize the chance of successful attacks.

The evaluator shall create such artefacts that with the highest likelihood of bypassing the PAD using the latest tools.

== Test Items
The evaluator shall create artefacts defined in all test items listed in the link:Face_Toolbox_Verification_List.adoc[Face Toolbox Verification List]. The Face Toolbox Verification List specifies the species types that must be created based on the type of biometric sensor.

PAD Toolbox Overview defines required number of attempts for the independent testing and maximum timeframe for both independent and penetration testing.

== Pass/Fail Criteria
IAPAR shall be less than the specified value in FIA_MBV_EXT.3.1 in any case. If additional Pass/Fail Criteria is defined in the test items, then the evaluator shall also follow them.

== Reference Information 
The Face Toolbox was created based on research papers listed in link:Face_Toolbox_References.adoc[Face Toolbox References]. The evaluator should read them before conducting the PAD testing because they include more detailed information about PAD test methods.
