= PAD-L1 Face Toolbox Inventory
:showtitle:
:revdate: 2025-01-14

This document contains the inventory of tools and materials that are used in the context of the L1-Face toolbox.

== Overview
This document specifies requirements for tools that are used to create face image artefacts. There are two types of tools and materials: Type 1 and Type 2. Not all tools or materials may have both types. Generally, the evaluator shall create "normal" quality face artefacts using Type 1 tools and high quality face artefacts with Type 2 tools. The requirements for each tool are specified in the following tables.

As cameras have a wide variability, the requirements for cameras are based on scoring provided by https://www.dxomark.com/[DXOMARK] sensor rankings. The intent is to provide an objective measure of whether the camera will meet the expectations for creating PAI. Similar objective criteria may be used with appropriate justifications.

The evaluator may use any tools and materials to create face artefacts as long as they meet requirements specified below. The evaluator may use any available services (e.g,. rental services) to prepare any tools in a cost effective way.

The evaluator may need to use other tools that are not specified here. 

Some examples:

* The evaluator may connect a camera to a TV directly to replay a face image on a 4K screen
* A camera video file could be imported to a PC from the camera and played directly from a 4K PC screen.
+
In such cases, the evaluator may use any PC and viewer software, however, the evaluator shall visually check the final image on the screen. If the evaluator sees any problem (e.g., choppy video playback because of an underpowered CPU), the evaluator shall replace the tools with an alternative that does not exhibit the problem. 
* The evaluator needs a PC to install and run reconstruction software to generate 3D images.
+
In such cases, the evaluator may use any PC that meets the software's hardware requirements.

== Tools Inventory
.Tool Requirements
[cols=".^1,.^1,3,3",options="header"]
|===

|ID
|Category
|Type 1
|Type 2    

|FA1-T.1 
|Camera    
a|Mobile device camera

* A mobile device where the https://www.dxomark.com/smartphones/[Smartphone Camera score] is at least 130.

* The evaluator shall not use the same mobile device on which the TOE is installed.
a|Camera

* A camera where the sensor meets the following measures (which can be found at https://www.dxomark.com/camera-sensors/)
** Native ISO: &#8804; 100
** Dynamic range at ISO 100: &#8805; 13 EV
** Color depth at ISO 100: &#8805; 25.0 bits
** Pixel count (in megapixels): &#8805; 30 MP
** SNR at ISO 100: &#8805; 42 dB
* A camera lens with the following https://www.dxomark.com/camera-lenses/[rankings]:
** Overall score: &#8805; 30
** Sharpness score: &#8805; 20

|FA1-T.2 
|Printer             
a|Small Office/Home Office Inkjet printer 

* A dedicated photo printer (not an all-in-one that also prints photos) no more than 5 years old.
** The printer's resolution must be able to print at least 2400x1200 DPI.
** OEM pigmented inks must be used.
** Use "High" print quality settings.
* Test user's face shall be printed on paper in full scale.
a|Professional print service

* Test user's face shall be printed on paper in full scale.
* The evaluator shall refer to publicly available information to select the best one (e.g., quality comparison report for professional print services). 
* The evaluator shall follow recommendations from professional print service (e.g., recommended image file size) to get the highest quality of photo print. 

|===

=== Camera Lens Usage Recommendations
For type 2 cameras with a lens, the following recommendations should be used:

* Always use lens stopped down at least 2 stops or more from widest aperture, preferably use f/8 if lighting allows at native ISO for the sensor being used.
* Match the equivalent focal length of the camera capturing the PAD data. If the focal length is unknown, use a focal length between 85 and 200 mm equivalent for full frame sensor.
* If the camera is used on a tripod, turn off vibration reduction in the lens and camera body if available.
* Always apply lens profile corrections in image software (Photoshop, Lightroom, GIMP, etc.):
** Geometric distortion corrections.
** Chromatic aberration corrections.

== Materials Inventory

.Materials Requirements
[cols=".^1,.^1,3,3",options="header"]
|===

|ID
|Category
|Type 1
|Type 2

|FA1-M.1 
|Print paper            
a|Matte paper 

* Paper shall be wide enough to include a test user's face in full scale

a|Paper recommend by professional print service selected

* Paper shall be wide enough to include a test user's face in full scale
* The evaluator shall select the best paper type to print the highest quality face images

|FA1-M.2 
|Screen              
a|Mobile device screen

* The evaluator shall use the same mobile device used for capturing test user's face
* Screen shall include the test user's full face and this face image shall be taken where the user holds the mobile device like a normal face verification
a|High resolution screen

* The evaluator shall use a UHD (4K) or higher resolution display (TV or computer monitor)
** Do not use Twisted Nematic (TN) or strobed backlight displays
** Recommended displays are In-Plane-Switching (IPS) or OLED
* Test user's face shall be displayed or replayed on the screen in full scale. The test user's face should be displayed as large as possible up to a 1:1 scale (for example a 47" TV screen should not display a 47" diagonal of the test user's face)

|===

== Environmental Conditions

.Environmental Requirements
[cols=".^1,.^1,3",options="header"]
|===

|ID
|Category
|Type 1

|FA1-E.1 
|Normal Environment - 300 lux
a|* Lighting conditions that correspond to classical indoor lighting measured around 300 lux
* Standard indoor background
* No backlighting
* No harsh or deep shadows should be visible on or across the face in the capture
* No other faces (live or picture) present in the capture

|===
