= Attack 2D Face 3-1

== Attack type
Replay video attack

=== Total Number of Species
This attack has *2* species to be tested.

== Overview
The evaluator records and replays a target user's face on a screen and presents it to the TOE.

== Input
Target user's face

== Tools
*Normal Quality*

* T.1, Type 1
* M.2, Type 1

== Recipe
The evaluator shall record a face image and replay it on a screen. 

The evaluator shall refer to publicly available information to change default settings of the camera (e.g., frames per second) to create clearer face artefacts.

The evaluator shall take at least three videos and select the best one to create each face artefact.

== Variations
=== Variation 1 (2D Face 3-2)
==== Attack Tools/Media
*High Quality*

* T.1, Type 2
* M.2, Type 2

== Prerequisite
The evaluator shall enrol test users first as described in the Face Toolbox Overview. If the ST covers multiple configurations for face unlock, the same test shall be performed for all configurations.

== Presentation
The evaluator shall present a mobile device screen on a tripod for 10 seconds as described in the Face Toolbox Overview.

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion
The evaluator should consider changing the following factors for penetration testing.

* Configuration of tool
+
The evaluator may, for example, change color effects of the camera to change the quality of the images. Such change may affect the texture of artefacts that may lead to false acceptance.

* Presentation method
+ 
As described in BIOSD, the evaluator may change the distance between the artefact and the TOE. 

=== Attack Potential Rating Suggestion
The attack potential that is required to build this artefact is summarized in the following table. See BIOSD Section 9 for more information about how to calculate the attack potential. 

[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
.Attack Potential 2D Face 3-1
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|<= one week
|1
|<= one day
|0
|1

|*Expertise*
|Layman
|0
|Layman
|0
|0
 
|*Knowledge of TOE*    
|Public
|0 
|N/A
|
|0

a|
*Window of Opportunity*

*(Access to TOE)* 
|Easy
|0
|Moderate
|4
|4

a|
*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|N/A
|
|Without notice
|0
|0

|*Equipment*
|Standard
|0 
|Standard
|0
|0

6+^.^|Total Attack Potential = 5 < Basic Attack Potential

|===


[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
.Attack Potential 2D Face 3-2
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|<= one week
|1
|<= one day
|0
|1

|*Expertise*
|Layman
|0
|Layman
|0
|0
 
|*Knowledge of TOE*    
|Public
|0 
|N/A
|
|0

a|
*Window of Opportunity*

*(Access to TOE)* 
|Easy
|0
|Moderate
|4
|4

a|
*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|N/A
|
|Without notice
|0
|0

|*Equipment*
|Standard
|0 
|Standard
|0
|0

6+^.^|Total Attack Potential = 5 < Basic Attack Potential

|===

== Pass Criteria
There is no additional criteria other than what is defined in BIOSD and PAD Toolbox Overview.