= Attack 3D Face 1-1

== Attack type
Printed face mask attack

=== Total Number of Species
This attack has *2* species to be tested.

== Overview
The evaluator captures and prints a target user's face on paper, bends the paper to wear it as a face mask, and presents it to the TOE.

== Input
Target user's face

== Attack Tools/Media
*Normal Quality*

* T.1, Type 1
* T.2, Type 1
* M.1, Type 1

== Recipe
The evaluator shall capture a face image and print it on paper. 

The evaluator shall refer to publicly available information to change default setting of the camera (e.g., picture size) and printer (e.g., output resolution) to create clearer face artefacts.

The evaluator shall take at least three photos and select the best one to create each face artefact.

== Variations

=== Variation 1 (3D Face 1-2)
==== Attack Tools/Media
*High Quality*

* T.1, Type 2
* T.2, Type 2
* M.1, Type 2

== Prerequisite
The evaluator shall enrol test users first as described in the Face Toolbox Overview. If the ST covers multiple configurations for face unlock, the same test shall be performed for all configurations.

== Presentation
The evaluator shall wear a printed face mask using tape or paste as described in the Face Toolbox Overview.

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion
The evaluator should consider changing the following factors for penetration testing.

* Configuration of tool
+
The evaluator may, for example, change color effects of the camera to change the quality of the images. Such change may affect the texture of artefacts that may lead to false acceptance.

* Presentation method
+ 
As described in BIOSD, the evaluator may change the distance between the artefact and the TOE. The evaluator may also make cuts to the printed photo (Cut photo attack) to allow for better 3D fit or to provide an option for live feedback when presenting the photo, for example removing the eyes or mouth and aligning with the wearer, or making a slit for the nose. The evaluator shall create a mask which approximates the size of their own head so as to properly appear as a full face (e.g. not showing the edge of the mask and then a portion of the wearer's own face, which may require the evaluator to consider physical characteristics of the test subject when determining the best presentation). The evaluator should attempt to maintain similar physical conditions to the test subject capture (such as distance from the sensor) when presenting the attack. 

=== Attack Potential Rating Suggestion
The attack potential that is required to build this artefact is summarized in the following table. See BIOSD Section 9 for more information about how to calculate the attack potential. 

[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
.Attack Potential 3D Face 1-1
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|<= one week
|1
|<= one day
|0
|1

|*Expertise*
|Layman
|0
|Layman
|0
|0
 
|*Knowledge of TOE*    
|Public
|0 
|N/A
|
|0

a|
*Window of Opportunity*

*(Access to TOE)* 
|Easy
|0
|Moderate
|4
|4

a|
*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|N/A
|
|Without notice
|0
|0

|*Equipment*
|Standard
|0 
|Standard
|0
|0

6+^.^|Total Attack Potential = 5 < Basic Attack Potential

|===


[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
.Attack Potential 3D Face 1-2
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|<= one week
|1
|<= one day
|0
|1

|*Expertise*
|Layman
|0
|Layman
|0
|0
 
|*Knowledge of TOE*    
|Public
|0 
|N/A
|
|0

a|
*Window of Opportunity*

*(Access to TOE)* 
|Easy
|0
|Moderate
|4
|4

a|
*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|N/A
|
|Without notice
|0
|0

|*Equipment*
|Standard
|0 
|Standard
|0
|0

6+^.^|Total Attack Potential = 5 < Basic Attack Potential

|===

== Pass Criteria
There is no additional criteria other than what is defined in BIOSD and PAD Toolbox Overview.
