= Attack L1-Face FA1-02-xx
:xrefstyle: short

== Attack type
Digital photo attack

=== Total Number of Species
This attack has *2* species to be tested.

== Overview
The evaluator captures and displays a target user's face on a screen and presents it to the TOE.

== Input
This attack assumes that target user’s facial images are available from the internet.

== Common Attack Environment
* FA1-E.1, Normal environment - 300 lux

== Common Recipe
The evaluator shall capture a face image and display it on a screen. The evaluator shall refer to publicly available information to change default settings of the camera (e.g., picture size) to create clearer face artefacts. The evaluator shall take at least three photos and select the best one to create each face artefact.

== Variations
The attack must be performed with each variation.

=== Variation 1 (L1-Face FA1-02-01)
*Normal Quality*

==== Attack Tools/Media
* FA1-T.1, Type 1 Mobile device camera
* FA1-M.2, Type 2 High resolution screen

=== Variation 2 (L1-Face FA1-02-02)
*High Quality*

==== Attack Tools/Media/Environment
* FA1-T.1, Type 2 Camera
* FA1-M.2, Type 2 High resolution screen

== Prerequisite
The evaluator shall enrol test users first as described in the Face Toolbox Overview. If the ST covers multiple configurations for face unlock, the same test shall be performed for all configurations.

== Presentation
The evaluator shall present the screen by hand as described in the Face Toolbox Overview.

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion
The evaluator should consider changing the following factors for penetration testing.

* Configuration of tool
+
The evaluator may, for example, change color effects of the camera to change the quality of the images. Such change may affect the texture of artefacts that may lead to false acceptance.

* Presentation method
+ 
As described in BIOSD, the evaluator may change the distance between the artefact and the TOE. 

=== Attack Potential Rating Suggestion
The attack potentials that are required to build the artefacts are summarized in the following table. See BIOSD Section 9 for more information about how to calculate attack potential.

Attack Potential values are shown in <<calculatedtable>>. Attack Potential values for Identification account for the time, expertise, etc. required to make the digital photo described in this attack. Attack potential for Exploitation corresponds to the effort to attack the TOE using the PAI in the actual environment (i.e., downloading the target facial image from the internet and attack the TOE using the digital photo). <<calculatedtable>> shows the final attack potential to rate the vulnerabilities and TOE resistance.

*All Variations*

.Calculated Attack Potential Face attack FA1-02-xx
[[calculatedtable]]
[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|⇐ one day
|1
|<= one hour
|0
|1

|*Expertise*
|Layman
|0
|Layman
|0
|0

|*Knowledge of TOE*    
|Public
|0 
|Public
|0 
|0

|*Equipment*
|Standard
|0 
|Standard
|0
|0

a|
*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|Not needed
|0
|Without notice (Easy)
|0
|0

a|
*Window of Opportunity*

*(Access to TOE)* 
|Easy
|0
|Moderate
|4
|4

|*Degree of Scrutiny*
|None
|0 
|None
|0
|0

6+^.^|Total Attack Potential = 5 < Basic Attack Potential

|===


== Pass Criteria
There is no additional criteria other than what is defined in BIOSD and PAD Toolbox Overview.
