= Attack L1-Face FA1-04-xx
:xrefstyle: short

== Attack type
Printed face mask attack

=== Total Number of Species
This attack has *2* species to be tested.

== Overview
The evaluator captures and prints a target user's face on paper, bends the paper to wear it as a face mask, and presents it to the TOE.

== Input
This attack assumes that target user's facial images are available from the internet.

== Common Attack Tools, Materials and Environment
* FA1-T.2, Photo Inkjet Printer or Service
* FA1-T.4, Lux meter
* FA1-M.1, Print paper
* FA1-E.1, Normal environment - 300 lux

== Common Recipe
The evaluator shall capture a face image and print it on paper. The evaluator shall refer to publicly available information to change default setting of the camera (e.g., picture size) and printer (e.g., output resolution) to create clearer face artefacts. The evaluator shall take at least three photos and select the best one to create each face artefact and cut the face out of the photo to construct the PAI.

== Variations
The attack must be performed with each variation.

=== Variation 1 (L1-Face FA1-04-01)
*Normal Quality*

==== Attack Tool
* FA1-T.1, Type 1 Camera

=== Variation 2 (L1-Face FA1-04-02)
*High Quality*

==== Attack Tools/Media/Environment
* FA1-T.1, Type 2 Camera

== Prerequisite
The evaluator shall enrol test users first as described in the Face Toolbox Overview. If the ST covers multiple configurations for face unlock, the same test shall be performed for all configurations.

== Presentation
The evaluator shall wear a printed face mask using tape or paste as described in the Face Toolbox Overview.

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion
The evaluator should consider changing the following factors for penetration testing.

* Configuration of tool
+
The evaluator may, for example, change color effects of the camera to change the quality of the images. Such change may affect the texture of artefacts that may lead to false acceptance.

* Presentation method
+ 
As described in BIOSD, the evaluator may change the distance between the artefact and the TOE. The evaluator may also make cuts to the printed photo (Cut photo attack) to allow for better 3D fit or to provide an option for live feedback when presenting the photo, for example removing the eyes or mouth and aligning with the wearer, or making a slit for the nose. The evaluator shall create a mask which approximates the size of their own head so as to properly appear as a full face (e.g. not showing the edge of the mask and then a portion of the wearer's own face, which may require the evaluator to consider physical characteristics of the test subject when determining the best presentation). The evaluator should attempt to maintain similar physical conditions to the test subject capture (such as distance from the sensor) when presenting the attack. 

=== Attack Potential Rating Suggestion
The attack potentials that are required to build the artefacts are summarized in the following table. See BIOSD Section 9 for more information about how to calculate attack potential.

Attack Potential values are shown in <<calculatedtable>>. Attack Potential values for Identification account for the time, expertise, etc. required to make the printed face mask described in this attack. Attack potential for Exploitation corresponds to the effort to attack the TOE using the PAI in the actual environment (i.e., downloading the target facial image from the internet and attack the TOE using the printed photo). <<calculatedtable>> shows the final attack potential to rate the vulnerabilities and TOE resistance.

*All Variations*

.Calculated Attack Potential Face attack FA1-04-xx
[[calculatedtable]]
[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|<= one day
|1
|<= one hour
|0
|1

|*Expertise*
|Layman
|0
|Layman
|0
|0

|*Knowledge of TOE*    
|Public
|0 
|Public
|0 
|0

|*Equipment*
|Standard
|0 
|Standard
|0
|0

a|
*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|Not needed
|0
|Without notice (Easy)
|0
|0

a|
*Window of Opportunity*

*(Access to TOE)* 
|Easy
|0
|Moderate
|4
|4

|*Degree of Scrutiny*
|None
|0 
|None
|0
|0

6+^.^|Total Attack Potential = 5 < Basic Attack Potential

|===

== Pass Criteria
There is no additional criteria other than what is defined in BIOSD and PAD Toolbox Overview.
