= Attack L1-Face FA1-01-xx

== Attack type
Printed photo attack

=== Total Number of Species
This attack has *2* species to be tested.

== Overview
The evaluator captures and prints target user's face on paper and presents it to the TOE.

== Input
Target user's face

== Recipe
The evaluator shall capture a face image and print it on paper. 

The evaluator shall refer to publicly available information to change default settings of the camera (e.g., picture size) and printer (e.g., output resolution) to create clearer face artefacts.

The evaluator shall take at least three photos and select the best one to create each face artefact.

== Variations
The attack must be performed with each variation.

=== Variation 1 (L1-Face FA1-01-01)
*Normal Quality*

==== Attack Tools/Media

* FA1-T.1, Type 1 Mobile device camera
* FA1-T.2, Type 1 Small Office/Home Office Inkjet printer
* FA1-M.1, Type 1 Matte paper

=== Variation 2 (L1-Face FA1-01-02)
*High Quality*

==== Attack Tools/Media

* FA1-T.1, Type 2 Camera
* FA1-T.2, Type 2 Professional print service
* FA1-M.1, Type 2 Paper recommend by professional print service selected

== Prerequisite
The evaluator shall enrol test users first as described in the Face Toolbox Overview. If the ST covers multiple configurations for face unlock, the same test shall be performed for all configurations.

== Presentation
The evaluator shall present a printed photo by hand as described in the Face Toolbox Overview.

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion
The evaluator should consider changing the following factors for penetration testing.

* Configuration of tool
+
The evaluator may, for example, change color effects of the camera to change the quality of the images. Such change may affect the texture of artefacts that may lead to false acceptance.

* Presentation method
+ 
As described in BIOSD, the evaluator may change the distance between the artefact and the TOE. In addition, the evaluator may deliberately warp a printed photo, trying to simulate facial motion (Warped photo attack). The evaluator may also remove the eye regions of a printed photo, align their own eyes behind the photo, and blink through the holes (Cut photo attack).  

=== Attack Potential Rating Suggestion
The attack potentials that are required to build the artefacts are summarized in the following table. See BIOSD Section 9 for more information about how to calculate attack potential. 

[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
.Attack Potential L1-Face FA1-01-01
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|<= one week
|1
|<= one day
|0
|1

|*Expertise*
|Layman
|0
|Layman
|0
|0
 
|*Knowledge of TOE*    
|Public
|0 
|N/A
|
|0

a|
*Window of Opportunity*

*(Access to TOE)* 
|Easy
|0
|Moderate
|4
|4

a|
*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|N/A
|
|Without notice
|0
|0

|*Equipment*
|Standard
|0 
|Standard
|0
|0

6+^.^|Total Attack Potential = 5 < Basic Attack Potential

|===


[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
.Attack Potential L1-Face FA1-01-02
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|<= one week
|1
|<= one day
|0
|1

|*Expertise*
|Layman
|0
|Layman
|0
|0
 
|*Knowledge of TOE*    
|Public
|0 
|N/A
|
|0

a|
*Window of Opportunity*

*(Access to TOE)* 
|Easy
|0
|Moderate
|4
|4

a|
*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|N/A
|
|Without notice
|0
|0

|*Equipment*
|Standard
|0 
|Standard
|0
|0

6+^.^|Total Attack Potential = 5 < Basic Attack Potential

|===

== Pass Criteria
There is no additional criteria other than what is defined in BIOSD and PAD Toolbox Overview.